Repository BE15-DevEagles/be15-fin-deveagles-beautifly, pull requests merged in 2025-07, with the labels that each got.

#327 [users] 회원 기능 구현 - 회원 가입 필수 값 누락
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/domain/aggregate/Staff.java
Labels: bug

#338 [messages] 문자 보내기 구현#307
  be15_DevEagles_BE/build.gradle
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsSendEvent.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/response/SmsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/SmsSendEventListener.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageKind.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/Sms.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/SmsRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/infrastructure/CoolSmsClient.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/main/resources/application.yml
Labels: enhancement

#346 [users] 회원 기능 구현 - 아이디 찾기 삭제 #217
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
  be15_DevEagles_BE/src/main/resources/application.yml
  be15_DevEagles_FE/src/features/users/components/FindIdModal.vue
  be15_DevEagles_FE/src/features/users/components/FindIdResModal.vue
  be15_DevEagles_FE/src/features/users/views/LoginView.vue
Labels: enhancement

#348 [messages]메시지 관련 기능 수정#342
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/SmsGroupSendEvent.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/SmsSendUnit.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsSendEvent.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/response/MessageSendResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/SmsSendEventListener.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/infrastructure/CoolSmsClient.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
Labels: enhancement

#350 [sales] 매출 기능 구현 - 회원권 매출 등록 기능 구현 #329
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/PrepaidPassSalesCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/SessionPassSalesCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PaymentsInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PrepaidPassSalesRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/SessionPassSalesRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/PrepaidPassSalesCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/SessionPassSalesCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Payments.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/PaymentsMethod.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Sales.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/PaymentsRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/PrepaidPassSalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/SalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/SessionPassSalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaPaymentsRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaPrepaidPassSalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaSalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaSessionPassSalesRepository.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
Labels: enhancement

#353 [itmes] 상품 로직 수정 - 1차 상품, 2차 상품 조회 로직 수 #351
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/SecondaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/SecondaryItem.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/PrimaryItemRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/SecondaryItemRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/PrimaryItemQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/SecondaryItemQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/PrimaryItemQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/SecondaryItemQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/items/components/BaseItemModal.vue
  be15_DevEagles_FE/src/features/items/components/ItemForm.vue
Labels: refactor

#358 [messages] 예약-발송-기능-구현 #349
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/Be15DevEaglesBeApplication.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/ScheduledSmsSender.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/SmsRepository.java
Labels: enhancement

#360 [users] 회원 기능 수정 - 회원 가입 매장 정보 검증 오류 #347
  be15_DevEagles_FE/src/features/users/components/EnrollStoreForm.vue
  be15_DevEagles_FE/src/features/users/views/SignUpView.vue
Labels: bug

#362 [messages] 메시지 조회 기능 구현 #361
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/SmsQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/request/SmsSearchRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/response/SmsDetailResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/response/SmsListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/SmsQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/SmsQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/SmsQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/SmsQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/SmsQueryServiceImplTest.java
Labels: enhancement

#363 [sales] 매출 기능 구현 - 매출 조회 기능 구현 #330
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/infrastructure/repository/JpaItemSalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/controller/SalesQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/request/SalesListFilterRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/PaymentsDTO.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/mapper/SalesMapper.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/SalesQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImpl.java
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/SalesMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImplTest.java
Labels: enhancement

#366 [messages] 템플릿 관련 기능 구현 #365
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageTemplateController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/MessageTemplateCreateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/MessageTemplateUpdateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/response/MessageTemplateResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageTemplateService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageTemplateServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageTemplate.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageTemplateType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/MessageTemplateRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/MessageTemplateQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageTemplateQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/MessageTemplateQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/MessageTemplateQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/MessageTemplateQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageTemplateServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/MessageTemplateQueryServiceImplTest.java
Labels: enhancement

#370 [sales] 매출 기능 구현 - 도메인 설정 #369
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/ItemSalesRepository.java
Labels: enhancement

#371 [sales] 매출 기능 구현 - 회원권 매출 환불 기능 구현 #356
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/SalesCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/SalesCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Sales.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SalesCommandServiceImplTest.java
Labels: enhancement

#376 [staffs] 직원 기능 구현 - 직원 등록 #367
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/domain/aggregate/AccessList.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/repository/AccessAuthRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/repository/AccessListRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/StaffCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/CreateStaffRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/response/StaffInfoResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/staffs/api/staffs.js
  be15_DevEagles_FE/src/features/staffs/views/StaffRegistView.vue
Labels: enhancement

#378 [schedules] 캘린더 스케줄 조회 #335
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/LeaveCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/PlanCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationSettingCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/PlanCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/DayOfWeekEnum.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ScheduleType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/CalendarScheduleQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/CustomerReservationSettingController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/LeaveQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/PlanQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/ReservationQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/ReservationSettingQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/request/CalendarRegularRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/request/CalendarScheduleRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/CalendarRegularResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/CalendarRenderedResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/CalendarScheduleResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/mapper/CalendarScheduleQueryMapper.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/CalendarScheduleQueryService.java
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/CalendarScheduleQueryMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/PlanCommandServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/CalendarScheduleQueryServiceTest.java
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
Labels: enhancement

#382 [staffs] 직원 기능 구현 - 직원 목록 조회 #377
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/StaffCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/repository/UserRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/controller/StaffQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/dto/request/GetStaffsListRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/dto/response/StaffsListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/infraStrucure/repository/StaffQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/infraStrucure/repository/StaffRepositoryImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/staffs/api/staffs.js
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
Labels: enhancement

#389 [membership] 회원권 기능 구현 - 고객 회원권 등록 기능 구현 #383
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/controller/PrepaidPassCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/controller/SessionPassCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/dto/request/CustomerPrepaidPassRegistRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/dto/request/CustomerSessionPassRegistRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/CustomerPrepaidPassCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/CustomerSessionPassCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerPrepaidPassCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerSessionPassCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerPrepaidPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerSessionPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerPrepaidPassRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerSessionPassRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/infrastructure/repository/JpaCustomerPrepaidPassRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/infrastructure/repository/JpaCustomerSessionPassRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/PrepaidPassQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/SessionPassQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PrepaidPassSalesRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/SessionPassSalesRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerPrepaidPassCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/command/application/service/impl/CustomerSessionPassCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
Labels: enhancement

#388 [analytics] DA 서버 - 분석모델, 대시보드 구현#387
  .gitignore
  be15_DevEagles_DA/README.md
  be15_DevEagles_DA/config/development.yaml
  be15_DevEagles_DA/create_preference_samples.py
  be15_DevEagles_DA/create_risk_samples.py
  be15_DevEagles_DA/poetry.lock
  be15_DevEagles_DA/pyproject.toml
  be15_DevEagles_DA/run_dashboard.py
  be15_DevEagles_DA/run_tests.py
  be15_DevEagles_DA/src/analytics/api/main.py
  be15_DevEagles_DA/src/analytics/assets/disable-react-warnings.js
  be15_DevEagles_DA/src/analytics/core/config.py
  be15_DevEagles_DA/src/analytics/dashboard/__init__.py
  be15_DevEagles_DA/src/analytics/dashboard/bi_dashboard.py
  be15_DevEagles_DA/src/analytics/dashboard/components/common.py
  be15_DevEagles_DA/src/analytics/dashboard/constants.py
  be15_DevEagles_DA/src/analytics/dashboard/theme.py
  be15_DevEagles_DA/src/analytics/dashboard/utils/decorators.py
  be15_DevEagles_DA/src/analytics/dashboard/utils/serializers.py
  be15_DevEagles_DA/src/analytics/etl/airflow_dag.py
  be15_DevEagles_DA/src/analytics/etl/base_extractors.py
  be15_DevEagles_DA/src/analytics/etl/beautifly_extractors.py
  be15_DevEagles_DA/src/analytics/etl/beautifly_pipeline.py
  be15_DevEagles_DA/src/analytics/etl/extractors.py
  be15_DevEagles_DA/src/analytics/etl/loaders.py
  be15_DevEagles_DA/src/analytics/etl/pipeline.py
  be15_DevEagles_DA/src/analytics/etl/transformers.py
  be15_DevEagles_DA/src/analytics/ml/churn_model.py
  be15_DevEagles_DA/src/analytics/models/beautifly_crm.py
  be15_DevEagles_DA/src/analytics/services/__init__.py
  be15_DevEagles_DA/src/analytics/services/churn_prediction.py
  be15_DevEagles_DA/src/analytics/services/cohort_retention.py
  be15_DevEagles_DA/tests/etl/__init__.py
  be15_DevEagles_DA/tests/etl/test_beautifly_etl.py
  be15_DevEagles_DA/tests/etl/test_etl.py
  be15_DevEagles_DA/tests/integration/__init__.py
  be15_DevEagles_DA/tests/integration/test_db_connection.py
  be15_DevEagles_DA/tests/services/__init__.py
  be15_DevEagles_DA/tests/services/test_cohort_retention.py
  be15_DevEagles_DA/tests/services/test_preference.py
  be15_DevEagles_DA/tests/services/test_risk_tagging.py
  be15_DevEagles_DA/tests/services/test_segmentation.py
  be15_DevEagles_DA/tests/unit/__init__.py
  be15_DevEagles_DA/tests/utils/__init__.py
  be15_DevEagles_DA/tests/utils/inspect_db_schema.py
  be15_DevEagles_DA/tests/utils/simple_test.py
  be15_DevEagles_DA/tests/utils/verify_segmentation.py
Labels: enhancement

#357 [notification] 예약알림 기능 구현#332
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/events/ReservationCreatedEvent.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/dto/CreateNotificationRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/domain/aggregate/Notification.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/domain/aggregate/NotificationType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/domain/repository/NotificationRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/query/application/dto/NotificationResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/query/application/dto/UnreadNotificationCountResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/query/application/service/NotificationQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/query/presentation/NotificationQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/query/repository/NotificationQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/handler/ReservationNotificationHandler.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationService.java
Labels: enhancement

#395 [staffs] 직원 기능 수정 - 직원 관리 페이지 수정 #384
  be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
  be15_DevEagles_FE/src/features/staffs/views/StaffRegistView.vue
Labels: bug

#397 [messages] 고객 신규 등록 자동 발송 기능 구현 #393
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/AutomaticMessageTriggerController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/AutomaticCreateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/SmsRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/AutomaticMessageTriggerService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageVariableProcessor.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/AutomaticMessageTriggerServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/AutomaticEventType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageTemplate.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/MessageTemplateRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageTemplateQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/MessageTemplateQueryRepositoryImpl.java
Labels: enhancement

#402 [messages] 테스트 코드 수정 #401
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
Labels: refactor

#416 [schedules] CustomUser 사용 #407
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/LeaveCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/PlanCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationSettingCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateLeaveRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreatePlanRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateRegularLeaveRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateRegularPlanRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/CreateReservationFullRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/LeaveCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/PlanCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/LeaveQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/PlanQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/request/LeaveListRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/LeaveQueryService.java
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/LeaveQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/PlanQueryMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/LeaveCommandServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/PlanCommandServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/LeaveQueryServiceTest.java
Labels: enhancement

#419 [membership] 회원권 기능 구현 - 고객 회원권 조회 기능 구현 #385
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/CustomerExpiringPrepaidPassQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/CustomerExpiringSessionPassQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/controller/CustomerMembershipQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/request/CustomerExpiringPrepaidPassFilterRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/request/CustomerExpiringSessionPassFilterRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/request/CustomerMemebershipFilterRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerExpiringMembershipResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerExpiringPrepaidPassResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerExpiringPrepaidPassResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerExpiringSessionPassResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerExpiringSessionPassResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerMembershipResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerMembershipResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerPrepaidPassDetailInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/CustomerSessionPassDetailInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/PrepaidPassInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/dto/response/SessionPassInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/mapper/CustomerMembershipMapper.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/service/CustomerExpiringPrepaidPassQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/service/CustomerExpiringSessionPassQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/service/CustomerMembershipQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/service/impl/CustomerExpiringPrepaidPassQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/service/impl/CustomerExpiringSessionPassQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/query/service/impl/CustomerMembershipQueryServiceImpl.java
  be15_DevEagles_BE/src/main/resources/mappers/features/membership/CustomerExpiringMemebershipMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/membership/CustomerExpiringPrepaidPassMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/membership/CustomerExpiringSessionPassMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/membership/CustomerMembershipMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/membership/CustomerPrepaidPassDetailMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/membership/CustomerSessionPassDetailMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/query/service/impl/CustomerExpiringPrepaidPassQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/query/service/impl/CustomerExpiringSessionPassQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/membership/query/service/impl/CustomerMembershipQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/membership/api/membership.js
  be15_DevEagles_FE/src/features/membership/components/CustomerMembershipDetailModal.vue
  be15_DevEagles_FE/src/features/membership/components/CustomerMembershipEditModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipExpiryFilterModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipExpiryTableForm.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipFilterModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipForm.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipTableForm.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesRegistModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSelectModal.vue
Labels: enhancement

#420 docs: 벡터 삽입용 샘플 데이터 생성
  docs/company-information.json
Labels: documentation

#424 [sales] 매출 기능 구현 - 상품 매출 등록 기능 구현 #373
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Customer.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerPrepaidPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerSessionPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerPrepaidPassRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/repository/CustomerSessionPassRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/controller/ItemSalesCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/ItemSalesRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/PaymentsInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/ItemSalesCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/ItemSalesRepository.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/PrepaidPassSalesCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/SessionPassSalesCommandServiceImplTest.java
Labels: enhancement

#427 [customer] 엘라스틱 서치 기능 추가 - 재인덱싱 코드 구현 #426
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/repository/CustomerJpaRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/CustomerElasticsearchController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/dto/response/ReindexStatus.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerQueryService.java
Labels: enhancement

#429 [staffsales] 직원 결산 기능 구현 - 직원별 결산 조회 #409
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/repository/StaffSalesQueryRepositoryImpl.java
  be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Labels: enhancement, refactor

#430 [shops] 매장 기능 수정 - 매장 설정 설명 폼 누락 #421
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/PutShopRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/repository/IndustryRepository.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/users/views/StoreSettingView.vue
Labels: bug

#434 [staffsales] 직원 결산 기능 구현 - 직원 상세결산 조회 #410
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/controller/StaffSalesQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffDetailSalesListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffPaymentsDetailSalesResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffPrimarySalesResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffSalesDetailListResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/StaffSecondarySalesResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/repository/StaffSalesQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/repository/StaffSalesQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/StaffSalesQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/StaffSalesQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/support/SalesCalculator.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/StaffSalesQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/staffsales/api/staffsales.js
  be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Labels: enhancement

#436 Feat/schedules/일정 휴무 api 연동#417
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/LeaveListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/PlanDetailResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/PlanListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/RegularPlanDetailResponse.java
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/LeaveQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/PlanQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/RegularPlanQueryMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/LeaveQueryServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/PlanQueryServiceTest.java
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
Labels: enhancement

#441 [profilelink] 프로필 링크 생성 페이지 구현#415
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/controller/ShopCommandController.java
  be15_DevEagles_FE/src/features/profilelink/api/shop.js
  be15_DevEagles_FE/src/features/profilelink/views/ProfileLinkView.vue
  be15_DevEagles_FE/src/features/profilelink/views/PublicProfileView.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#444 [notifications] 예약알림 구현#332
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/controller/NotificationController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationSseService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/handler/ReservationNotificationHandler.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationCommandServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationSseServiceTest.java
Labels: enhancement

#439 [schedules] 캘린더 크기 조절 #437
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
Labels: enhancement

#450 [schedules] 예약 목록 관련 api 연동 #440
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/ReservationSearchMapper.xml
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
Labels: enhancement

#457 [schedules] 예약 상태 변경 연동 #453
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/UpdateReservationStatusRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationService.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationServiceTest.java
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
Labels: enhancement

#464 [schedules] 예약 설정 연동 #459
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/controller/ReservationSettingCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/dto/request/UpdateReservationSettingRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationSettingCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationSettingInitializer.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/ReservationSettingQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationSettingCommandServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
Labels: enhancement

#468 [staffsales] 직원 결산 기능 구현 - 목표매출 설정 #413
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/controller/StaffSalesCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/dto/StaffSalesTargetInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/dto/request/GetSalesTargetRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/dto/request/SetIncentiveRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/dto/request/SetSalesTargetRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/dto/response/IncentiveListResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/dto/response/SalesTargetListResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/service/SalesTargetCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/service/impl/IncentiveCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/service/impl/SalesTargetCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/domain/aggregate/SalesTarget.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/domain/aggregate/StaffSalesSettingType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/repository/IncentiveRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/command/repository/SalesTargetRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/controller/StaffSalesQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/dto/response/StaffPaymentsSalesResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/dto/response/StaffSalesSummaryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/dto/response/StaffSecondarySalesResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/repository/SalesQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/repository/SalesQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/repository/SalesTargetQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/repository/SalesTargetQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/repository/StaffSalesQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/repository/StaffSalesQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/service/SalesTargetQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/service/impl/SalesTargetQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/service/impl/StaffSalesQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/staffsales/query/service/support/SalesCalculator.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/service/impl/IncentiveCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/staffsales/command/application/service/impl/SalesTargetCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/staffsales/query/service/impl/SalesTargetQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/staffsales/query/service/impl/StaffSalesQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/staffsales/api/staffsales.js
  be15_DevEagles_FE/src/features/staffsales/components/IncentiveSettingModal.vue
  be15_DevEagles_FE/src/features/staffsales/components/TargetSalesSettingModal.vue
  be15_DevEagles_FE/src/features/staffsales/composables/useFlattenSales.js
  be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Labels: enhancement, refactor

#469 [staffs] 직원 기능 수정 - 직원 목록 조회 시 민감 정보 제외 #405
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/dto/response/StaffListInfo.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/dto/response/StaffsListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/infraStrucure/repository/StaffQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/query/infraStrucure/repository/StaffQueryRepositoryImpl.java
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
Labels: bug

#471 [shops] 매장 기능 수정 - sns 삭제 에러 수정 #438
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/PutShopRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/repository/SnsRepository.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/users/query/application/service/StaffQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/users/views/StoreSettingView.vue
Labels: bug

#465 [analytics] 통계/분석 도메인 - 백엔드 구현 #442
  .gitignore
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/controller/StatisticsController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/AdvancedSalesStatisticsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/SalesStatisticsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/SalesSummaryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/StatisticsRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/repository/StatisticsQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/repository/StatisticsQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/service/StatisticsQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/service/StatisticsQueryServiceImpl.java
Labels: enhancement

#476 [analytics] DTO 업로드 누락 수정 #475
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/analytics/application/dto/HighRiskCustomer.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/DailyVisitorStatisticsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/HourlyVisitorStatisticsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/ReservationRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/ReservationStatisticsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/statistics/query/dto/ReservationSummaryResponse.java
Labels: bug

#478 [auth] 인증인가 기능 구현 - SpringSecurity 적용 #472
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
  be15_DevEagles_FE/src/features/users/api/users.js
  be15_DevEagles_FE/src/features/users/views/LoginView.vue
  be15_DevEagles_FE/src/routes/index.js
  be15_DevEagles_FE/src/store/auth.js
Labels: enhancement

#480 [schedules] 스케줄 등록 연동 #461
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/components/LeaveForm.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
  be15_DevEagles_FE/src/features/schedules/components/SelectSecondaryItemModal.vue
Labels: enhancement

#481 [messages] 메시지 보내기 api 연동 #456
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/WebSocketAuthInterceptor.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageSettingsCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/SmsQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/dto/response/SmsListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/SmsQueryRepositoryImpl.java
  be15_DevEagles_FE/src/features/messages/api/message.js
  be15_DevEagles_FE/src/features/messages/components/MessageItem.vue
  be15_DevEagles_FE/src/features/messages/components/MessageStats.vue
  be15_DevEagles_FE/src/features/messages/components/drawer/CustomerSelectDrawer.vue
  be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/ReservationSendModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/SendConfirmModal.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
  be15_DevEagles_FE/src/features/messages/views/SettingsView.vue
Labels: enhancement

#485 swagger-설정
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatRoomController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/controller/ChatMessageQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/controller/ChatRoomQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/AutomaticMessageTriggerController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageTemplateController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/MessageTemplateQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/SmsQueryController.java
Labels: refactor

#488 swagger-설정
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatRoomController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/controller/ChatMessageQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/controller/ChatRoomQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageTemplateController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/MessageTemplateQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/controller/SmsQueryController.java
Labels: refactor

#492 [staffs] 직원 설정 접근권한 영역 숨김
  be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
Labels: refactor

#493 [notifications] 공지사항 알림 기능 구현#458
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/controller/NotificationCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/controller/NotificationController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/dto/CreateNoticeRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/application/service/NotificationCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/command/domain/aggregate/Notification.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/notifications/query/presentation/NotificationQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/handler/ReservationNotificationHandler.java
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/components/layout/TheHeader.vue
  be15_DevEagles_FE/src/composables/useToast.js
  be15_DevEagles_FE/src/features/notifications/components/NotificationList.vue
  be15_DevEagles_FE/src/features/notifications/composables/useNotifications.js
Labels: enhancement

#500 [staffs] 직원 기능 수정 - 직원 퇴사 버그 수정
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/StaffCommandServiceImpl.java
  be15_DevEagles_FE/src/features/staffs/components/StaffForm.vue
  be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
Labels: bug

#502 [sales] 매출 기능 구현 - 매출 수정 및 환불 API 연동 #496
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/request/SalesListFilterRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/ItemSalesDetailResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/PrepaidPassSalesDetailResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SessionPassSalesDetailResponse.java
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/ItemSalesQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/PrepaidPassSalesQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/SalesMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/SessionPassSalesQueryMapper.xml
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/features/membership/components/MembershipDetailModal.vue
  be15_DevEagles_FE/src/features/sales/api/sales.js
  be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesEditModal.vue
  be15_DevEagles_FE/src/features/sales/components/SalesFilterModal.vue
  be15_DevEagles_FE/src/features/sales/components/SalesForm.vue
  be15_DevEagles_FE/src/features/sales/components/SalesTableForm.vue
  be15_DevEagles_FE/src/features/sales/styles/SalesDetailModal.css
Labels: enhancement

#499 [notifications] 공지사항 알림 - 불필요한 주석 삭제#458
  be15_DevEagles_FE/src/features/notifications/api/notifications.js
  be15_DevEagles_FE/src/features/notifications/components/NotificationList.vue
  be15_DevEagles_FE/src/features/notifications/composables/useNotifications.js
Labels: chore

#504 [schedules] 고객 예약 연동 #463
  be15_DevEagles_FE/src/features/profilelink/views/ProfileLinkView.vue
  be15_DevEagles_FE/src/features/profilelink/views/PublicProfileView.vue
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/components/StaffCard.vue
  be15_DevEagles_FE/src/features/schedules/routes.js
  be15_DevEagles_FE/src/features/schedules/views/DesignerListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
  be15_DevEagles_FE/src/features/schedules/views/StaffListView.vue
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
Labels: enhancement

#512 [analytics] 파이썬 서버 - duck db 오류코드삭제#511
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/controller/CustomerCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/AssignSegmentToCustomerRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/CreateSegmentRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/service/CustomerSegmentSchedulerService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/service/CustomerSegmentUpdateService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/service/SegmentService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Segment.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/CustomerRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/SegmentByCustomerRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/SegmentRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/repository/CustomerRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/SegmentServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/SegmentCustomerQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/dto/response/SegmentCustomersResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerQueryService.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/application/service/CustomerSegmentUpdateServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/SegmentCustomerQueryControllerTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceSegmentImplTest.java
  be15_DevEagles_DA/Dockerfile
  be15_DevEagles_DA/config/staging.yaml
  be15_DevEagles_DA/docker-compose-etl.yml
  be15_DevEagles_DA/env.example
  be15_DevEagles_DA/src/airflow/dags/crm_to_duckdb_etl.py
  be15_DevEagles_DA/src/analytics/core/database.py
  be15_DevEagles_DA/src/analytics/core/duckdb_client.py
  be15_DevEagles_DA/src/analytics/services/churn_prediction.py
  be15_DevEagles_DA/src/analytics/services/churn_prediction_duckdb.py
  be15_DevEagles_DA/src/analytics/services/cohort_retention.py
  be15_DevEagles_DA/src/analytics/services/cohort_retention_duckdb.py
  be15_DevEagles_DA/src/analytics/services/segmentation.py
  be15_DevEagles_DA/src/analytics/services/segmentation_duckdb.py
  be15_DevEagles_DA/tests/services/test_churn_prediction.py
  be15_DevEagles_DA/tests/services/test_churn_prediction_duckdb.py
  be15_DevEagles_DA/tests/services/test_segmentation.py
  be15_DevEagles_DA/tests/services/test_segmentation_duckdb.py
  be15_DevEagles_FE/src/components/layout/TheHeader.vue
Labels: bug

#530 [messages] 프로필-링크-로그-클릭-관련-api #520
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageClickRedirectController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageClickService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageClickServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/Sms.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageClickLinkLogRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/MessageClickLinkRepository.java
  be15_DevEagles_BE/src/main/resources/application.yml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageClickServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/messages/api/message.js
  be15_DevEagles_FE/src/features/messages/components/MessageItem.vue
  be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/ReservationSendModal.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
Labels: enhancement

#533 [schedules] 매출 등록 연결 #507
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/ReservationDetailResponse.java
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/ReservationQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/ReservationSearchMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/ReservationQueryServiceTest.java
  be15_DevEagles_FE/src/features/sales/api/sales.js
  be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemsSelectModal.vue
  be15_DevEagles_FE/src/features/schedules/api/schedules.js
  be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/LeaveForm.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
  be15_DevEagles_FE/src/features/schedules/components/SelectSecondaryItemModal.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
Labels: enhancement

#539 [schedules] 캘린더 스타일 변경 #537
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
Labels: bug

#538 [messages] 예약-등록-시-문자-자동-발송 #535
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/controller/ChatRoomController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatRoomServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/command/domain/aggregate/ChatRoom.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/config/WebSocketAuthInterceptor.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/chat/query/dto/response/ChatRoomSummaryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/AutomaticMessageTriggerController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageVariableProcessor.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/ScheduledSmsSender.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/AutomaticMessageTriggerServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/MessageTemplateQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/repository/impl/SmsQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/MessageTemplateQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/CalendarScheduleQueryService.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/chat/command/application/service/impl/ChatRoomServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/query/service/impl/SmsQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/command/application/service/ReservationServiceTest.java
  be15_DevEagles_FE/src/features/chat/composables/socket.js
Labels: enhancement

#540 [workflow] 프론트 백엔드 연동 - 워크플로우 자동화#345
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/controller/WorkflowCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/dto/request/ToggleWorkflowCommand.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/domain/aggregate/Workflow.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/infrastructure/service/WorkflowCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowQueryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/controller/WorkflowQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/service/WorkflowQueryServiceImpl.java
  be15_DevEagles_FE/src/components/common/BaseTagSelector.vue
  be15_DevEagles_FE/src/features/campaigns/components/CampaignForm.vue
  be15_DevEagles_FE/src/features/coupons/components/CompactCouponSelector.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponSelectorModal.vue
  be15_DevEagles_FE/src/features/workflows/api/workflows.js
  be15_DevEagles_FE/src/features/workflows/components/WorkflowConfigSidebar.vue
  be15_DevEagles_FE/src/features/workflows/components/WorkflowFormBase.vue
  be15_DevEagles_FE/src/features/workflows/composables/useWorkflowForm.js
  be15_DevEagles_FE/src/features/workflows/views/WorkflowCreate.vue
  be15_DevEagles_FE/src/features/workflows/views/WorkflowEdit.vue
  be15_DevEagles_FE/src/features/workflows/views/WorkflowList.vue
Labels: enhancement

#548 [sales] 매출 조회 버그 수정 #547
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/dto/request/ItemSalesRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/repository/ItemSalesRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/controller/ItemSalesQureyController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/ItemSalesDetailDTO.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/ItemSalesDetailResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/ItemSalesListDTO.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/dto/response/SalesListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/mapper/ItemSalesQueryMapper.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/mapper/SalesMapper.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/SalesQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImpl.java
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/ItemSalesQueryMapper.xml
  be15_DevEagles_BE/src/main/resources/mappers/features/sales/SalesMapper.xml
  be15_DevEagles_FE/src/features/membership/components/CustomerMembershipDetailModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipExpiryFilterModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipForm.vue
  be15_DevEagles_FE/src/features/sales/api/sales.js
  be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
  be15_DevEagles_FE/src/features/sales/components/RefundDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/SalesFilterModal.vue
  be15_DevEagles_FE/src/features/sales/components/SalesTableForm.vue
Labels: bug

#550 [sales] 매출 조회 디버깅#547
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/GlobalExceptionHandler.java
  be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
Labels: bug, enhancement

#552 [chat] 채팅 웹소켓 버그 - 웹소켓 로그아웃시 세션 유지되는 문제 수정#551
  be15_DevEagles_FE/src/components/layout/TheHeader.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: bug

#555 feat : aws-배포
  be15_DevEagles_BE/.github/workflows/deploy.yml
  be15_DevEagles_BE/build.gradle
Labels: enhancement

#559 feat : aws-배포
  be15_DevEagles_BE/.github/workflows/deploy.yml
Labels: enhancement

#557 Create deploy.yml
  .github/workflows/deploy.yml
Labels: enhancement

#561 Create deploy.yml
  be15_DevEagles_BE/.github/workflows/deploy.yml
Labels: enhancement

#560 feat: aws
  .github/workflows/deploy.yml
Labels: enhancement

#566 feat: aws
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/command/application/service/impl/ItemSalesCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/sales/query/service/impl/SalesQueryServiceImplTest.java
Labels: bug

#567 feat : aws-배포
  be15_DevEagles_BE/Procfile
Labels: enhancement

#568 feat : aws-배포
  .github/workflows/deploy.yml
Labels: enhancement

#569 feat : aws-배포
  .github/workflows/deploy.yml
Labels: enhancement

#572 Update build.gradle
  be15_DevEagles_BE/build.gradle
Labels: enhancement

#573 Update build.gradle
  be15_DevEagles_BE/build.gradle
Labels: enhancement

#576 feat : aws-배포
  be15_DevEagles_BE/Procfile
Labels: enhancement

#565 [schedules] 수정 삭제 등록 시 재조회 #556
  be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
Labels: bug

#584 fix : 비밀번호 초기화 이메일 인증 실패 시 비밀번호 변경 비활성화
  be15_DevEagles_FE/src/features/users/views/EmailVerifyPwdView.vue
Labels: bug

#585 Update deploy.yml
  .github/workflows/deploy.yml
Labels: enhancement

#587 Update deploy.yml
  .github/workflows/deploy.yml
Labels: enhancement

#582 [analytics] 파이썬 서버 배포 준비, 세그먼트 기능 스케쥴링 등록 #581
  .github/workflows/main.yml
  be15_DevEagles_DA/DEPLOYMENT.md
  be15_DevEagles_DA/Dockerfile
  be15_DevEagles_DA/Dockerrun.aws.json
  be15_DevEagles_DA/Makefile
  be15_DevEagles_DA/config.yaml
  be15_DevEagles_DA/config/local.yaml.example
  be15_DevEagles_DA/config/production.yaml
  be15_DevEagles_DA/docker-compose-etl.yml
  be15_DevEagles_DA/docker-compose.yml
  be15_DevEagles_DA/etl_requirements.txt
  be15_DevEagles_DA/health_check.py
  be15_DevEagles_DA/pyproject.toml
  be15_DevEagles_DA/requirements.txt
  be15_DevEagles_DA/run_dashboard.py
  be15_DevEagles_DA/run_dashboard_duckdb.py
  be15_DevEagles_DA/scripts/run_dashboard.sh
  be15_DevEagles_DA/scripts/run_scheduler.sh
  be15_DevEagles_DA/scripts/run_segment_updater.sh
  be15_DevEagles_DA/scripts/run_webserver.sh
  be15_DevEagles_DA/segment_update.py
  be15_DevEagles_DA/src/analytics/core/config.py
  be15_DevEagles_DA/src/analytics/core/database.py
  be15_DevEagles_DA/src/analytics/core/logging.py
  be15_DevEagles_DA/src/analytics/dashboard/bi_dashboard_duckdb.py
  be15_DevEagles_DA/src/analytics/services/__init__.py
  be15_DevEagles_DA/src/analytics/services/churn_prediction.py
  be15_DevEagles_DA/src/analytics/services/churn_prediction_duckdb.py
  be15_DevEagles_DA/src/analytics/services/cohort_retention_duckdb.py
  be15_DevEagles_DA/src/analytics/services/segment_management.py
  be15_DevEagles_DA/src/analytics/services/segment_scheduler.py
  be15_DevEagles_DA/supervisord.conf
  docs/company-information.json
Labels: documentation, enhancement

#588 Feat/analytics/파이썬 서버 배포 준비#581
  .github/workflows/main.yml
  be15_DevEagles_DA/Dockerfile
Labels: bug
