Repository BE15-DevEagles/be15-fin-deveagles-beautifly, pull requests merged in 2025-06, with the labels that each got.

#11 [CI/CD] 템플릿 업데이트 #9
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  .github/workflows/bug-issue-notify.yml
Labels: enhancement

#13 Revert "[CI/CD] 템플릿 업데이트 #9"
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  .github/workflows/bug-issue-notify.yml
Labels: enhancement

#18 [CI/CD] 템플릿 업데이트
  README.md
Labels: enhancement

#19 test:revised workflow test
  .github/pull_request_template.md
  README.md
Labels: enhancement

#23 [chore] backend - 프로젝트 기본설정 #21
  .idea/.gitignore
  .idea/be15-fin-deveagles.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  be15_DevEagles_BE/.gitattributes
  be15_DevEagles_BE/.gitignore
  be15_DevEagles_BE/build.gradle
  be15_DevEagles_BE/gradle/wrapper/gradle-wrapper.jar
  be15_DevEagles_BE/gradle/wrapper/gradle-wrapper.properties
  be15_DevEagles_BE/gradlew
  be15_DevEagles_BE/gradlew.bat
  be15_DevEagles_BE/settings.gradle
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/Be15DevEaglesBeApplication.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/JpaConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/ModelMapperConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/WebConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/ApiResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/PagedResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/PagedResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/Pagination.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/temp
  be15_DevEagles_BE/src/main/resources/application.yml
  be15_DevEagles_BE/src/main/resources/mappers/features/temp
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/Be15DevEaglesBeApplicationTests.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/temp
Labels: chore

#22 [chore] frontend 프로젝트 기본 설정 #20
  .gitignore
  .husky/pre-commit
  be15_DevEagles_FE/.lintstagedrc.json
  be15_DevEagles_FE/.prettierrc
  be15_DevEagles_FE/README.md
  be15_DevEagles_FE/eslint.config.js
  be15_DevEagles_FE/index.html
  be15_DevEagles_FE/jsconfig.json
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/postcss.config.js
  be15_DevEagles_FE/public/favicon.ico
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/assets/base.css
  be15_DevEagles_FE/src/assets/css/components.css
  be15_DevEagles_FE/src/assets/css/styleguide.css
  be15_DevEagles_FE/src/components/common/index.js
  be15_DevEagles_FE/src/components/icons/IconCommunity.vue
  be15_DevEagles_FE/src/components/icons/IconDocumentation.vue
  be15_DevEagles_FE/src/components/icons/IconEcosystem.vue
  be15_DevEagles_FE/src/components/icons/IconSupport.vue
  be15_DevEagles_FE/src/components/icons/IconTooling.vue
  be15_DevEagles_FE/src/features/README.md
  be15_DevEagles_FE/src/images/suri/chat.png
  be15_DevEagles_FE/src/images/suri/customer.png
  be15_DevEagles_FE/src/images/suri/dataanalysis.png
  be15_DevEagles_FE/src/images/suri/employee.png
  be15_DevEagles_FE/src/images/suri/items.png
  be15_DevEagles_FE/src/images/suri/marketing.png
  be15_DevEagles_FE/src/images/suri/messages.png
  be15_DevEagles_FE/src/images/suri/notification.png
  be15_DevEagles_FE/src/images/suri/sales.png
  be15_DevEagles_FE/src/images/suri/schedule.png
  be15_DevEagles_FE/src/images/suri/team_logo-cutout-notext.png
  be15_DevEagles_FE/src/images/suri/team_logo-cutout.png
  be15_DevEagles_FE/src/images/suri/team_logo.png
  be15_DevEagles_FE/src/main.js
  be15_DevEagles_FE/src/plugins/ChartPlugin.js
  be15_DevEagles_FE/src/plugins/axios.js
  be15_DevEagles_FE/src/plugins/logger.js
  be15_DevEagles_FE/src/routes/index.js
  be15_DevEagles_FE/src/store/index.js
  be15_DevEagles_FE/tailwind.config.js
  be15_DevEagles_FE/vite.config.js
Labels: chore

#25 [chore] backend - log 설정 #24
  .husky/pre-commit
  be15_DevEagles_BE/.gitignore
  be15_DevEagles_BE/build.gradle
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/Be15DevEaglesBeApplication.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/controller/LogTestController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/ApiResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/PagedResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/dto/PagedResult.java
  be15_DevEagles_BE/src/main/resources/application.yml
  be15_DevEagles_BE/src/main/resources/logback-spring.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/Be15DevEaglesBeApplicationTests.java
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/assets/base.css
  be15_DevEagles_FE/src/assets/css/styleguide.css
  be15_DevEagles_FE/src/main.js
Labels: chore

#26 [chore] logback profile 없을 시 fallback 설정
  be15_DevEagles_BE/src/main/resources/logback-spring.xml
Labels: chore

#31 feat: 공통 컴포넌트 생성 - 헤더, 레이아웃, 사이드바 #30
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/assets/css/tooltip.css
  be15_DevEagles_FE/src/components/common/TheHeader.vue
  be15_DevEagles_FE/src/components/common/TheLayout.vue
  be15_DevEagles_FE/src/components/common/TheSidebar.vue
  be15_DevEagles_FE/src/components/common/index.js
  be15_DevEagles_FE/src/components/icons/BarChartIcon.vue
  be15_DevEagles_FE/src/components/icons/BellIcon.vue
  be15_DevEagles_FE/src/components/icons/CalendarIcon.vue
  be15_DevEagles_FE/src/components/icons/ChevronDownIcon.vue
  be15_DevEagles_FE/src/components/icons/ChevronRightIcon.vue
  be15_DevEagles_FE/src/components/icons/DollarIcon.vue
  be15_DevEagles_FE/src/components/icons/HomeIcon.vue
  be15_DevEagles_FE/src/components/icons/IconCommunity.vue
  be15_DevEagles_FE/src/components/icons/IconDocumentation.vue
  be15_DevEagles_FE/src/components/icons/IconEcosystem.vue
  be15_DevEagles_FE/src/components/icons/IconSupport.vue
  be15_DevEagles_FE/src/components/icons/IconTooling.vue
  be15_DevEagles_FE/src/components/icons/LinkIcon.vue
  be15_DevEagles_FE/src/components/icons/MegaphoneIcon.vue
  be15_DevEagles_FE/src/components/icons/MessageCircleIcon.vue
  be15_DevEagles_FE/src/components/icons/SearchIcon.vue
  be15_DevEagles_FE/src/components/icons/SettingsIcon.vue
  be15_DevEagles_FE/src/components/icons/ShoppingBagIcon.vue
  be15_DevEagles_FE/src/components/icons/TagIcon.vue
  be15_DevEagles_FE/src/components/icons/UserIcon.vue
  be15_DevEagles_FE/src/components/icons/UsersIcon.vue
  be15_DevEagles_FE/src/components/icons/index.js
  be15_DevEagles_FE/src/main.js
  be15_DevEagles_FE/src/routes/index.js
  be15_DevEagles_FE/src/views/Home.vue
Labels: enhancement

#33 [common] 공통 컴포넌트 수정 - 툴팁 문구 수정 #30
  be15_DevEagles_FE/src/components/common/TheSidebar.vue
Labels: enhancement

#43 [common] 공통 - 기본 컴포넌트 생성#42
  be15_DevEagles_FE/src/components/common/BaseAlert.vue
  be15_DevEagles_FE/src/components/common/BaseBadge.vue
  be15_DevEagles_FE/src/components/common/BaseButton.vue
  be15_DevEagles_FE/src/components/common/BaseCard.vue
  be15_DevEagles_FE/src/components/common/BaseDrawer.vue
  be15_DevEagles_FE/src/components/common/BaseForm.vue
  be15_DevEagles_FE/src/components/common/BaseLoading.vue
  be15_DevEagles_FE/src/components/common/BaseModal.vue
  be15_DevEagles_FE/src/components/common/BaseTable.vue
  be15_DevEagles_FE/src/components/common/BaseToast.vue
  be15_DevEagles_FE/src/components/common/Pagaination.vue
  be15_DevEagles_FE/src/components/common/index.js
  be15_DevEagles_FE/src/components/layout/TheHeader.vue
  be15_DevEagles_FE/src/components/layout/TheLayout.vue
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
Labels: enhancement

#44 [coupons] 쿠폰 목록 - 쿠폰 목록 페이지 및 컴포넌트 구현 #41
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/assets/css/components.css
  be15_DevEagles_FE/src/assets/css/styleguide.css
  be15_DevEagles_FE/src/components/common/BaseButton.vue
  be15_DevEagles_FE/src/components/common/BaseConfirm.vue
  be15_DevEagles_FE/src/components/common/BasePopover.vue
  be15_DevEagles_FE/src/components/common/index.js
  be15_DevEagles_FE/src/components/layout/index.js
  be15_DevEagles_FE/src/features/coupons/CouponForm.vue
  be15_DevEagles_FE/src/features/coupons/CouponList.vue
  be15_DevEagles_FE/src/features/coupons/index.js
  be15_DevEagles_FE/src/features/coupons/routes.js
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#49 [workflows] 워크플로우 컴포넌트 구현 - 목록 구현 및 공통 코드 리팩토링 #48
  be15_DevEagles_FE/src/assets/css/buttons.css
  be15_DevEagles_FE/src/assets/css/empty-state.css
  be15_DevEagles_FE/src/assets/css/list-components.css
  be15_DevEagles_FE/src/assets/css/toggle.css
  be15_DevEagles_FE/src/components/common/BaseButton.vue
  be15_DevEagles_FE/src/components/common/Pagaination.vue
  be15_DevEagles_FE/src/components/icons/EditIcon.vue
  be15_DevEagles_FE/src/components/icons/TrashIcon.vue
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
  be15_DevEagles_FE/src/composables/useListManagement.js
  be15_DevEagles_FE/src/composables/useToast.js
  be15_DevEagles_FE/src/constants/messages.js
  be15_DevEagles_FE/src/constants/mockData.js
  be15_DevEagles_FE/src/features/README.md
  be15_DevEagles_FE/src/features/campaigns/views/CampaignList.vue
  be15_DevEagles_FE/src/features/coupons/views/CouponList.vue
  be15_DevEagles_FE/src/features/workflows/routes.js
  be15_DevEagles_FE/src/features/workflows/views/WorkflowList.vue
  be15_DevEagles_FE/src/routes/index.js
  be15_DevEagles_FE/src/utils/formatters.js
Labels: enhancement

#50 Feat/schedule/예약 관련 화면 구현#28
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/features/schedule/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedule/router.js
  be15_DevEagles_FE/src/features/schedule/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedule/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedule/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/schedule/views/ScheduleCalendarView.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#51 [user] 로그인 화면 구현 #47
  be15_DevEagles_FE/src/features/users/route.js
  be15_DevEagles_FE/src/features/users/views/LoginView.vue
  be15_DevEagles_FE/src/images/logo_name_navy.png
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#65 [analytics] 매출 통계 컴포넌트 - 매출 통계 페이지, 다크 모드 구현 #54
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/assets/css/styleguide.css
  be15_DevEagles_FE/src/components/common/DarkModeToggle.vue
  be15_DevEagles_FE/src/components/layout/TheLayout.vue
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
  be15_DevEagles_FE/src/composables/useDarkMode.js
  be15_DevEagles_FE/src/features/analytics/components/StatCard.vue
  be15_DevEagles_FE/src/features/analytics/components/charts/BaseChart.vue
  be15_DevEagles_FE/src/features/analytics/composables/useSalesAnalytics.js
  be15_DevEagles_FE/src/features/analytics/config/chartOptions.js
  be15_DevEagles_FE/src/features/analytics/constants/chartConstants.js
  be15_DevEagles_FE/src/features/analytics/styles/analytics.css
  be15_DevEagles_FE/src/features/analytics/styles/charts.css
  be15_DevEagles_FE/src/features/analytics/utils/formatters.js
  be15_DevEagles_FE/src/features/analytics/utils/mockDataGenerator.js
  be15_DevEagles_FE/src/features/analytics/views/SalesAnalytics.vue
  be15_DevEagles_FE/src/features/coupons/views/CouponList.vue
  be15_DevEagles_FE/src/main.js
  be15_DevEagles_FE/src/plugins/darkMode.js
  be15_DevEagles_FE/src/routes/index.js
  be15_DevEagles_FE/tailwind.config.js
  package.json
Labels: enhancement

#74 [analytics] 통계 컴포넌트 - 예약률 통계 페이지 구현 #55
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
  be15_DevEagles_FE/src/features/analytics/components/charts/BaseChart.vue
  be15_DevEagles_FE/src/features/analytics/composables/useUsageAnalytics.js
  be15_DevEagles_FE/src/features/analytics/config/usageChartOptions.js
  be15_DevEagles_FE/src/features/analytics/styles/usage.css
  be15_DevEagles_FE/src/features/analytics/utils/mockUsageDataGenerator.js
  be15_DevEagles_FE/src/features/analytics/views/UsageAnalytics.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#82 Feat/coupons/쿠폰 상세 조회#57
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/assets/css/primevue-theme.css
  be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
  be15_DevEagles_FE/src/components/common/VCalendarWrapper.vue
  be15_DevEagles_FE/src/features/campaigns/components/CampaignForm.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponDetailModal.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponForm.vue
  be15_DevEagles_FE/src/features/coupons/index.js
  be15_DevEagles_FE/src/features/coupons/views/CouponList.vue
  be15_DevEagles_FE/src/main.js
  be15_DevEagles_FE/src/plugins/axios.js
Labels: enhancement

#83 feat: 메시지 즉시 보내기 UI/UX 구현 #70
  be15_DevEagles_FE/src/features/messages/components/MessageFilter.vue
  be15_DevEagles_FE/src/features/messages/components/MessageItem.vue
  be15_DevEagles_FE/src/features/messages/components/MessageStats.vue
  be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/SendConfirmModal.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
Labels: enhancement

#84 [users] 유저 컴포넌트 구현 - 매장 설정 #80
  be15_DevEagles_FE/src/features/users/components/AddressSearch.vue
  be15_DevEagles_FE/src/features/users/components/EnrollStoreForm.vue
  be15_DevEagles_FE/src/features/users/views/SignUpView.vue
  be15_DevEagles_FE/src/features/users/views/StoreSettingView.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#88 [staffs] 직원 컴포넌트 구현 - 직원 관리 목록 #81
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#91 [analytics] 개발 설정 파이썬 DB 설정#90
  .gitignore
  be15_DevEagles_DA/env.example
  be15_DevEagles_DA/pyproject.toml
  be15_DevEagles_DA/src/analytics/api/main.py
  be15_DevEagles_DA/src/analytics/api/routes/__init__.py
  be15_DevEagles_DA/src/analytics/api/routes/health.py
  be15_DevEagles_DA/src/analytics/cli.py
  be15_DevEagles_DA/src/analytics/core/config.py
  be15_DevEagles_DA/src/analytics/core/database.py
  be15_DevEagles_DA/src/analytics/core/logging.py
Labels: chore

#93 docs: README 초안 작성
  README.md
Labels: documentation

#94 [common] 공통 컴포넌트 - Pagination 클래스명 수정 #92
  be15_DevEagles_FE/src/components/common/Pagination.vue
  be15_DevEagles_FE/src/components/common/index.js
  be15_DevEagles_FE/src/features/campaigns/views/CampaignList.vue
  be15_DevEagles_FE/src/features/coupons/views/CouponList.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
  be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/staffs/views/StaffListView.vue
  be15_DevEagles_FE/src/features/workflows/views/WorkflowList.vue
Labels: refactor

#104 [analytics] 파이썬 서버 - 고객 방문, 선호 시술, 이탈위험 모델 구현 #97
  be15_DevEagles_DA/config/development.yaml
  be15_DevEagles_DA/config/local.yaml.example
  be15_DevEagles_DA/config/production.yaml
  be15_DevEagles_DA/config/staging.yaml
  be15_DevEagles_DA/src/analytics/cli.py
  be15_DevEagles_DA/src/analytics/models/__init__.py
  be15_DevEagles_DA/src/analytics/models/analytics.py
  be15_DevEagles_DA/src/analytics/models/base.py
  be15_DevEagles_DA/src/analytics/models/crm.py
Labels: enhancement

#105 [analytics] ETL, Airflow DAG 구현#98
  be15_DevEagles_DA/pyproject.toml
  be15_DevEagles_DA/src/analytics/cli.py
  be15_DevEagles_DA/src/analytics/etl/__init__.py
  be15_DevEagles_DA/src/analytics/etl/airflow_dag.py
  be15_DevEagles_DA/src/analytics/etl/base.py
  be15_DevEagles_DA/src/analytics/etl/config.py
  be15_DevEagles_DA/src/analytics/etl/extractors.py
  be15_DevEagles_DA/src/analytics/etl/loaders.py
  be15_DevEagles_DA/src/analytics/etl/pipeline.py
  be15_DevEagles_DA/src/analytics/etl/transformers.py
  be15_DevEagles_DA/src/analytics/models/crm.py
  be15_DevEagles_DA/test_etl.py
Labels: enhancement

#106 feat: 메시지 템플릿 조회 모달 구현 #96
  be15_DevEagles_FE/src/features/messages/components/MessageStats.vue
  be15_DevEagles_FE/src/features/messages/components/TemplateSelectDrawer.vue
  be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
  be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Labels: enhancement

#108 [analytics] 파이썬 서버 - 고객 세그멘테이션, 선호도 로직#99
  be15_DevEagles_DA/create_preference_samples.py
  be15_DevEagles_DA/simple_test.py
  be15_DevEagles_DA/src/analytics/cli.py
  be15_DevEagles_DA/src/analytics/models/base.py
  be15_DevEagles_DA/src/analytics/services/__init__.py
  be15_DevEagles_DA/src/analytics/services/preference.py
  be15_DevEagles_DA/src/analytics/services/segmentation.py
  be15_DevEagles_DA/test_preference.py
  be15_DevEagles_DA/test_segmentation.py
  be15_DevEagles_DA/verify_segmentation.py
Labels: enhancement

#109 [staffs] 직원 컴포넌트 구현 - 직원 상세 #102
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/features/staffs/components/StaffForm.vue
  be15_DevEagles_FE/src/features/staffs/components/StaffPermission.vue
  be15_DevEagles_FE/src/features/staffs/route.js
  be15_DevEagles_FE/src/features/staffs/views/StaffDetailView.vue
  be15_DevEagles_FE/src/features/users/components/ProfileUpload.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement, refactor

#113 [analytics] 이탈 위험 태깅 구현#100
  be15_DevEagles_DA/create_risk_samples.py
  be15_DevEagles_DA/src/analytics/cli.py
  be15_DevEagles_DA/src/analytics/models/crm.py
  be15_DevEagles_DA/src/analytics/services/__init__.py
  be15_DevEagles_DA/src/analytics/services/risk_tagging.py
  be15_DevEagles_DA/test_risk_tagging.py
Labels: enhancement

#115 [messages] 템플릿 등록 모달 구현하기#107
  be15_DevEagles_FE/src/features/messages/components/TemplateItem.vue
  be15_DevEagles_FE/src/features/messages/components/modal/TemplateCreateModal.vue
  be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Labels: enhancement

#120 [schedules] 캘린더 수정 #103
  be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
Labels: enhancement

#121 [common] 비즈니스 예외 코드 등록
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/BusinessException.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCodeType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/GlobalExceptionHandler.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/temp
Labels: chore

#124 [messages] 템플릿 삭제 모달 구현 #123
  be15_DevEagles_FE/src/features/messages/components/modal/TemplateDeleteModal.vue
  be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Labels: enhancement

#127 [coupon] 쿠폰 기능 - 유효성 검증, 할인 계산 및 반환 #125
  be15_DevEagles_BE/build.gradle
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/QueryDslConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/command/dto/CreateCouponCommand.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/command/dto/UpdateCouponCommand.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/dto/CouponApplicationRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/dto/CouponApplicationResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/dto/CouponDto.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/dto/CouponValidationResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/entity/Coupon.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/query/dto/CouponQuery.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/query/dto/CouponResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/query/service/CouponQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/repository/CouponQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/repository/CouponRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponDiscountCalculator.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/utils/CouponCodeGenerator.java
Labels: enhancement

#128 [coupon] 쿠폰 기능 - 쿠폰 서비스 컨트롤러 구현#117
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/command/service/CouponCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/command/service/CouponCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/controller/CouponController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/controller/CouponValidationController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/query/service/CouponQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/repository/CouponQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponApplicationService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponValidationService.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/command/service/CouponCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/query/service/CouponQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponApplicationServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponDiscountCalculatorTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponValidationServiceTest.java
Labels: enhancement

#130 [membership] 회원권 - 페이지 구현 #62
  be15_DevEagles_FE/src/features/membership/components/MembershipForm.vue
  be15_DevEagles_FE/src/features/membership/view/MembershipView.vue
Labels: enhancement

#132 [coupon] 쿠폰 엔티티 Access 레벨 누락 수정
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/entity/Coupon.java
Labels: bug

#140 [customer] 고객 목록 페이지 구현#85
  be15_DevEagles_FE/src/components/icons/FilterIcon.vue
  be15_DevEagles_FE/src/components/icons/SortIcon.vue
  be15_DevEagles_FE/src/features/customer/routes.js
  be15_DevEagles_FE/src/features/customer/views/CustomerListView.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#143 [schedules] 직원 일정 휴무 목록 조회 #77
  be15_DevEagles_FE/src/components/common/BaseTable.vue
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
  be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleLeaveView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanView.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#148 [coupon] 도메인 레이어 격리 및 서비스 레이어 분리#135
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/application/validation/CouponApplicationService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/application/validation/CouponValidationService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/common/CouponResponseFactory.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/common/CouponResponseFactoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/domain/entity/Coupon.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/domain/service/CouponDiscountCalculator.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/domain/vo/DiscountResult.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/infrastructure/repository/CouponQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/infrastructure/repository/CouponRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/coupons/presentation/controller/CouponController.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponApplicationServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/service/CouponDiscountCalculatorTest.java
Labels: refactor

#151 [schedules] 스케줄 등록 모달 #145
  be15_DevEagles_FE/src/features/schedules/components/LeaveForm.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
Labels: enhancement

#152 [campaign] 캠페인 기능 - 캠페인 생성, 조회, 삭제 #111
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/application/controller/CampaignCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/application/dto/request/CreateCampaignRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/application/dto/response/CampaignResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/application/service/CampaignCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/application/service/CampaignCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/domain/aggregate/Campaign.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/domain/repository/CampaignRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/infrastructure/repository/CampaignJpaRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/command/infrastructure/repository/CampaignRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/query/controller/CampaignQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/query/dto/request/CampaignSearchRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/query/dto/response/CampaignQueryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/query/repository/CampaignQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/query/service/CampaignQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/campaigns/query/service/impl/CampaignQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/campaigns/command/application/service/CampaignCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/campaigns/query/service/impl/CampaignQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/application/command/CouponCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/application/query/CouponSearchQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/application/validation/CouponApplicationServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/application/validation/CouponValidationServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/coupons/domain/service/CouponDiscountCalculatorTest.java
Labels: enhancement

#157 [customer] 고객 도메인 - 고객, 태그, 고객태그 고객등급 엔티티 구현 #156
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Customer.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/CustomerGrade.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Tag.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/TagByCustomer.java
Labels: enhancement

#162 [schedules] 예약 설정 페이지 #144
  be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#165 [schedules] 디자이너 선택 페이지 #163
  be15_DevEagles_FE/src/features/schedules/components/DesignerCard.vue
  be15_DevEagles_FE/src/features/schedules/routes.js
  be15_DevEagles_FE/src/features/schedules/views/DesignerListView.vue
  be15_DevEagles_FE/src/images/suri/designer-profile1.png
  be15_DevEagles_FE/src/images/suri/designer-profile2.png
  be15_DevEagles_FE/src/images/suri/designer-profile3.png
  be15_DevEagles_FE/src/images/suri/designer-profile4.png
  be15_DevEagles_FE/src/images/suri/designer-profile5.png
  be15_DevEagles_FE/src/images/suri/designer-profile6.png
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#167 [schedules] 고객 예약 페이지 구현 #164
  be15_DevEagles_FE/src/features/schedules/components/DesignerCard.vue
  be15_DevEagles_FE/src/features/schedules/routes.js
  be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
Labels: enhancement

#173 [chat]채팅 - 채팅 목록 구현 #160
  be15_DevEagles_FE/src/components/icons/ListIcon.vue
  be15_DevEagles_FE/src/components/icons/NewIcon.vue
  be15_DevEagles_FE/src/components/layout/TheLayout.vue
  be15_DevEagles_FE/src/features/chat/components/ChatInput.vue
  be15_DevEagles_FE/src/features/chat/components/ChatListView.vue
  be15_DevEagles_FE/src/features/chat/components/ChatMessages.vue
  be15_DevEagles_FE/src/features/chat/components/ChatModal.vue
Labels: enhancement

#174 [customer] 고객 컴포넌트 - 신규고객등록모달 구현#142
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/features/customer/components/CustomerColumnSettingsDrawer.vue
  be15_DevEagles_FE/src/features/customer/components/CustomerCreateDrawer.vue
  be15_DevEagles_FE/src/features/customer/views/CustomerListView.vue
Labels: enhancement

#183 [schedules] UI UX 개선 #166
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/components/common/BaseModal.vue
  be15_DevEagles_FE/src/features/schedules/components/DesignerCard.vue
  be15_DevEagles_FE/src/features/schedules/components/LeaveDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/LeaveForm.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/PlanForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationDetailModal.vue
  be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
  be15_DevEagles_FE/src/features/schedules/views/DesignerListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationHistoryView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleCalendarView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleLeaveView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanView.vue
  be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
Labels: enhancement

#185 [coupon] 버그 수정 - 시간 초기화 버그#168
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImplTest.java
  be15_DevEagles_FE/index.html
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/components/common/BaseButton.vue
  be15_DevEagles_FE/src/components/common/BaseForm.vue
  be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponForm.vue
Labels: bug

#186 [staffs] 직원 컴포넌트 구현 - 목표 매출 #139
  be15_DevEagles_FE/src/features/staffsales/components/TargetSalesSettingModal.vue
  be15_DevEagles_FE/src/features/staffsales/view/StaffSalesListView.vue
Labels: enhancement, refactor

#189 [common] 코드 수정 - Datepicker 관련 불필요한 코드 삭제
  be15_DevEagles_FE/index.html
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/assets/css/primevue-theme.css
  be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
  be15_DevEagles_FE/src/main.js
Labels: refactor

#190 [users] 유저 컴포넌트 구현 - 본인 인증 페이지 #187
  be15_DevEagles_FE/src/features/users/route.js
  be15_DevEagles_FE/src/features/users/views/EmailVerifyView.vue
Labels: enhancement

#191 [users] 유저 컴포넌트 구현 - 본인 인증 비밀번호 변경 페이지 #188
  be15_DevEagles_FE/src/features/users/components/PasswordEditForm.vue
  be15_DevEagles_FE/src/features/users/route.js
  be15_DevEagles_FE/src/features/users/views/EmailPwdEditView.vue
  be15_DevEagles_FE/src/features/users/views/EmailVerifyPwdView.vue
Labels: enhancement

#193 [sales] 매출 컴포넌트 구현 - 매출 모달 구현 #133
  be15_DevEagles_FE/src/features/sales/components/ItemSalesDeleteModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemSalesDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemSalesEditModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemSalesRefundModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemsSalesRegistModal.vue
  be15_DevEagles_FE/src/features/sales/components/ItemsSelectModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesDeleteModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesEditModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesRefundModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSalesRegistModal.vue
  be15_DevEagles_FE/src/features/sales/components/MembershipSelectModal.vue
  be15_DevEagles_FE/src/features/sales/components/RefundDetailModal.vue
  be15_DevEagles_FE/src/features/sales/components/SalesFilterModal.vue
  be15_DevEagles_FE/src/features/sales/components/SalesTableForm.vue
  be15_DevEagles_FE/src/features/sales/styles/SalesDetailModal.css
  be15_DevEagles_FE/src/features/sales/styles/SalesItemsModal.css
  be15_DevEagles_FE/src/features/sales/styles/SalesMembershipModal.css
Labels: enhancement

#196 [membership] 회원권 페이지 수정 - UI 개선 #195
  be15_DevEagles_FE/src/features/membership/components/CustomerMembershipDetailModal.vue
  be15_DevEagles_FE/src/features/membership/components/CustomerMembershipEditModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipDeleteModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipDetailModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipEditModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipExpiryFilterModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipExpiryTableForm.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipFilterModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipForm.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipRegistModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipTableForm.vue
  be15_DevEagles_FE/src/features/membership/styles/MembershipModal.css
  be15_DevEagles_FE/src/features/sales/components/SalesFilterModal.vue
Labels: refactor

#197 [item] 상품 페이지 수정 - UI 개선 #194
  be15_DevEagles_FE/src/features/item/components/ItemForm.vue
  be15_DevEagles_FE/src/features/item/components/PrimaryDeleteModal.vue
  be15_DevEagles_FE/src/features/item/components/PrimaryEditModal.vue
  be15_DevEagles_FE/src/features/item/components/PrimaryRegistModal.vue
  be15_DevEagles_FE/src/features/item/components/SecondaryDeleteModal.vue
  be15_DevEagles_FE/src/features/item/components/SecondaryEditModal.vue
  be15_DevEagles_FE/src/features/item/components/SecondaryRegistModal.vue
Labels: refactor

#209 [common] 공통 컴포넌트 수정 - 네비게이션바 변경 #201
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
Labels: refactor

#222 [schedules] 전체적인 수정 #198
  be15_DevEagles_FE/package.json
  be15_DevEagles_FE/src/features/schedules/components/ScheduleCalendar.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationRequestsView.vue
  be15_DevEagles_FE/src/features/schedules/views/ScheduleLeaveView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanView.vue
  be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: bug, enhancement

#227 [users] 엔터티 생성 - 회원, 매장 관련 entity 생성 #221
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/domain/aggregate/AccessAuth.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/domain/aggregate/AccessList.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Incentive.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Industry.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/ProductType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/SNS.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/SNSType.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/SalesTarget.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/domain/aggregate/Staff.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/domain/aggregate/StaffStatus.java
Labels: enhancement

#229 [users] 엔터티 수정 - AccessListEntity 수정 #221
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/domain/aggregate/AccessList.java
Labels: refactor

#233 [customer] 고객 도메인 엔티티 수정 반영 - customer, customerGrade, tag #230
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/controller/CustomerGradeController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/controller/TagController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/CreateCustomerGradeRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/CreateCustomerRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/CreateTagRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/UpdateCustomerGradeRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/request/UpdateTagRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/response/CustomerCommandResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/response/CustomerGradeResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/application/dto/response/TagResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Customer.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/CustomerGrade.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/aggregate/Tag.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/CustomerGradeRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/domain/repository/TagRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerGradeCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerTagServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/TagCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/dto/response/CustomerDetailResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/dto/response/CustomerResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/repository/CustomerDetailQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/repository/CustomerListQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerGradeQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/TagQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/CustomerGradeQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/service/TagQueryService.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerGradeCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/CustomerTagServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/command/infrastructure/service/TagCommandServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerGradeQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/CustomerQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/customers/query/infrastructure/service/TagQueryServiceImplTest.java
Labels: bug

#234 [schedules] 초기 세팅 #228
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/DayOfWeekEnum.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/Leave.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/Plan.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/RegularLeave.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/RegularPlan.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/Reservation.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ReservationDetail.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ReservationSetting.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/command/domain/aggregate/ReservationStatusName.java
Labels: enhancement

#245 [workflow] 워크플로 백엔드 기능 구현 - 워크플로우 실행 엔진#244
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/ActionExecutorService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/CustomerFilterService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/TriggerCheckService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowExecutionService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowScheduler.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/domain/aggregate/Workflow.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/domain/aggregate/WorkflowExecution.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/CustomerFilterServiceTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/service/WorkflowExecutionServiceTest.java
Labels: enhancement

#254 [Common] SecurityConfig 설정 #252
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
Labels: chore

#255 [usrs] 회원 기능 구현 - 회원가입 #212
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/controller/ShopCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/ShopCreateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/ValidBizNumberRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/domain/aggregate/Shop.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/repository/ShopRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/ShopAndUserCreateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/UserCreateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/dto/request/ValidCheckRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/service/UserCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/domain/aggregate/Staff.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/repository/UserRepository.java
  be15_DevEagles_BE/src/main/resources/application.yml
Labels: enhancement

#257 [items] 상품 기능 구현 - 1차 상품 등록 기능 구현 #203
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/dto/request/PrimaryItemRegistRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/PrimaryItemServiceCommand.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/Category.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/PrimaryItem.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/SecondaryItem.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/PrimaryItemRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/infrastructure/repository/JpaPrimaryItemRepository.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/item/components/PrimaryRegistModal.vue
  be15_DevEagles_FE/src/features/items/api/items.js
  be15_DevEagles_FE/src/features/items/components/BaseItemModal.vue
  be15_DevEagles_FE/src/features/items/components/ItemForm.vue
  be15_DevEagles_FE/src/features/items/components/PrimaryDeleteModal.vue
  be15_DevEagles_FE/src/features/items/components/PrimaryEditModal.vue
  be15_DevEagles_FE/src/features/items/components/PrimaryRegistModal.vue
  be15_DevEagles_FE/src/features/items/components/SecondaryDeleteModal.vue
  be15_DevEagles_FE/src/features/items/components/SecondaryEditModal.vue
  be15_DevEagles_FE/src/features/items/components/SecondaryRegistModal.vue
  be15_DevEagles_FE/src/features/items/views/ItemView.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipEditModal.vue
  be15_DevEagles_FE/src/features/membership/components/MembershipRegistModal.vue
  be15_DevEagles_FE/src/routes/index.js
Labels: enhancement

#262 [workflow] 워크플로우 백엔드 - 조회 기능#259
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/infrastructure/repository/WorkflowJpaDataRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/request/WorkflowSearchRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowQueryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowStatsResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/dto/response/WorkflowSummaryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/application/service/WorkflowQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/controller/WorkflowQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/domain/repository/WorkflowQueryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/repository/WorkflowQueryRepositoryImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/service/WorkflowQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/workflows/query/infrastructure/service/WorkflowQueryServiceImplTest.java
Labels: enhancement

#263 [membership] 회원권 - 회원권 관련 Entity 생성 #261
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerPrepaidPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/CustomerSessionPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/PrepaidPass.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/membership/command/domain/aggregate/SessionPass.java
Labels: enhancement

#265 [customer] 고객 태그 설정 모달 #251
  be15_DevEagles_FE/src/features/customer/components/AddTagDrawer.vue
  be15_DevEagles_FE/src/features/customer/components/CustomerTagSettingsDrawer.vue
  be15_DevEagles_FE/src/features/customer/components/EditTagDrawer.vue
  be15_DevEagles_FE/src/features/customer/views/CustomerListView.vue
Labels: enhancement

#269 [sales] 매출 - 매출 관련 Entity 생성 #264
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/ItemSales.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Payment.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/PaymentMethod.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/PrepaidPassSales.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/Sales.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/sales/command/domain/aggregate/SessionPassSales.java
Labels: enhancement

#270 [messages] 템플릿 목록 UI 수정#247
  be15_DevEagles_FE/src/components/layout/TheSidebar.vue
  be15_DevEagles_FE/src/features/messages/components/TemplateItem.vue
  be15_DevEagles_FE/src/features/messages/components/TemplateSelectDrawer.vue
  be15_DevEagles_FE/src/features/messages/components/modal/MessageSendModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/ReservationSendModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/SendConfirmModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/TemplateCreateModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/TemplateDeleteModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/TemplateDetailModal.vue
  be15_DevEagles_FE/src/features/messages/components/modal/TemplateEditModal.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
  be15_DevEagles_FE/src/features/messages/views/SettingsView.vue
  be15_DevEagles_FE/src/features/messages/views/TemplateListView.vue
Labels: refactor

#274 [schedules] 매장 생성 시 예약 설정 추가 #238
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
Labels: enhancement

#272 [common] Playwright - 기본 설정 및 깃헙 워크플로우 등록 #268
  .gitignore
  be15_DevEagles_FE/package.json
Labels: chore

#280 [items] 상품 기능 구현 - 1차 상품 수정 기능 구현 #205
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/dto/request/PrimaryItemRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/PrimaryItemCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/PrimaryItem.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImplTest.java
Labels: enhancement

#281 [items] 상품 기능 구현 - 1차 상품 조회 기능 구현 #210
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/SecondaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/PrimaryItemRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/PrimaryItemQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/dto/response/PrimaryItemResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/PrimaryItemQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PriamryItemQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PriamryItemQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/items/api/items.js
  be15_DevEagles_FE/src/features/items/components/BaseItemModal.vue
  be15_DevEagles_FE/src/features/items/components/ItemForm.vue
  be15_DevEagles_FE/src/features/items/components/PrimaryEditModal.vue
Labels: enhancement

#282 [coupon] 윈도우 모달 생성 - 쿠폰 폼, 캠페인 폼 및 페이지 수정#279
  be15_DevEagles_FE/src/components/common/BaseWindow.vue
  be15_DevEagles_FE/src/components/common/PrimeDatePicker.vue
  be15_DevEagles_FE/src/features/campaigns/components/CampaignForm.vue
  be15_DevEagles_FE/src/features/campaigns/views/CampaignList.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponDetailModal.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponForm.vue
  be15_DevEagles_FE/src/features/coupons/views/CouponList.vue
Labels: enhancement

#283 chore: Playwright 기본 설정 누락 재업로드 #268
  .github/workflows/playwright.yml
  be15_DevEagles_FE/playwright-report/index.html
  be15_DevEagles_FE/playwright.config.js
  be15_DevEagles_FE/tests/example.spec.js
Labels: chore

#285 Delete be15_DevEagles_FE/playwright-report directory
  be15_DevEagles_FE/playwright-report/index.html
Labels: bug

#284 [items] 상품 기능 구현 - 1차 상품 삭제 기능 구현 #207
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/controller/PrimaryItemCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/PrimaryItemCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/aggregate/PrimaryItem.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/command/application/service/impl/PrimaryItemCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/items/api/items.js
  be15_DevEagles_FE/src/features/items/components/ItemForm.vue
  be15_DevEagles_FE/src/features/items/components/PrimaryDeleteModal.vue
Labels: enhancement

#288 [messages] 자동 설정 UI 구현 #271
  be15_DevEagles_FE/src/features/messages/components/drawer/AutoSendSettingDrawer.vue
  be15_DevEagles_FE/src/features/messages/components/drawer/CustomerSelectDrawer.vue
  be15_DevEagles_FE/src/features/messages/components/drawer/TemplateSelectDrawer.vue
  be15_DevEagles_FE/src/features/messages/components/modal/AutoSendSettingModal.vue
  be15_DevEagles_FE/src/features/messages/views/MessagesListView.vue
  be15_DevEagles_FE/src/features/messages/views/SettingsView.vue
Labels: enhancement

#289 [items] 상품 기능 구현 - 2차 상품 조회 기능 구현 #211
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/command/domain/repository/SecondaryItemRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/controller/SecondaryItemQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/dto/response/SecondaryItemResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/SecondaryItemQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImpl.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/PrimaryItemQueryServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/items/query/service/impl/SecondaryItemQueryServiceImplTest.java
  be15_DevEagles_FE/src/features/items/api/items.js
  be15_DevEagles_FE/src/features/items/components/ItemForm.vue
  be15_DevEagles_FE/src/features/items/components/SecondaryRegistModal.vue
Labels: enhancement

#292 [coupon] 쿠폰 프론트 - 선택창 디자인, 생성 모달 연결#286
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/command/application/controller/WorkflowCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockCouponService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockCustomerEventService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockCustomerQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockMessageQueryService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockMessageService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/workflows/execution/infrastructure/service/MockNotificationService.java
  be15_DevEagles_FE/src/components/common/BaseWindow.vue
  be15_DevEagles_FE/src/components/common/CompactTemplateSelector.vue
  be15_DevEagles_FE/src/components/common/TemplateForm.vue
  be15_DevEagles_FE/src/components/common/TemplateSelectorModal.vue
  be15_DevEagles_FE/src/components/icons/PlusIcon.vue
  be15_DevEagles_FE/src/components/icons/TicketIcon.vue
  be15_DevEagles_FE/src/components/icons/XIcon.vue
  be15_DevEagles_FE/src/components/icons/index.js
  be15_DevEagles_FE/src/features/coupons/components/CompactCouponSelector.vue
  be15_DevEagles_FE/src/features/coupons/components/CouponSelectorModal.vue
  be15_DevEagles_FE/src/features/coupons/index.js
  be15_DevEagles_FE/src/features/workflows/components/WorkflowConfigSidebar.vue
  be15_DevEagles_FE/src/features/workflows/components/WorkflowFormBase.vue
Labels: enhancement

#293 [common] playwright - 실패 플로우 수정
  .github/workflows/playwright.yml
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/AcquisitionChannelController.java
Labels: chore

#296 chore: playwright 워크플로우 수정
  .github/workflows/playwright.yml
Labels: chore

#297 [customer] 비정상 파일 삭제 - query에 acquisition 컨트롤러 제거
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/customers/query/controller/AcquisitionChannelController.java
Labels: bug

#302 [schedules] 일정 기능 개선 #298
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/controller/PlanQueryController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/dto/response/PlanListResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/mapper/PlanQueryMapper.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/PlanQueryService.java
  be15_DevEagles_BE/src/main/resources/mappers/features/schedules/PlanQueryMapper.xml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/schedules/query/service/PlanQueryServiceTest.java
Labels: bug

#308 [customer] 고객상세정보모달#175
  be15_DevEagles_FE/src/components/common/BaseDrawer.vue
  be15_DevEagles_FE/src/features/customer/components/CustomerEditDrawer.vue
  be15_DevEagles_FE/src/features/customer/views/CustomerListView.vue
Labels: chore

#310 [users] 회원 기능 구현 - 회원가입 API 연동 #260
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/controller/ShopCommandController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/request/ShopCreateRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/dto/response/GetIndustryResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/IndustryRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/shops/command/application/service/ShopCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/users/api/users.js
  be15_DevEagles_FE/src/features/users/components/AddressSearch.vue
  be15_DevEagles_FE/src/features/users/components/EnrollStoreForm.vue
  be15_DevEagles_FE/src/features/users/components/EnrollUserForm.vue
  be15_DevEagles_FE/src/features/users/views/SignUpView.vue
Labels: enhancement

#312 [users] 회원 기능 구현 - 로그인 기능 구현 #214
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/RedisConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/request/LoginRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/dto/response/TokenResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/model/CustomUser.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/CustomUserDetailsService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/RefreshTokenServiceImpl.java
  be15_DevEagles_BE/src/main/resources/application.yml
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/application/service/AuthServiceImplTest.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/shops/command/application/ShopCommandServiceImplTest.java
  be15_DevEagles_FE/src/features/users/api/users.js
  be15_DevEagles_FE/src/features/users/views/LoginView.vue
Labels: enhancement

#317 feat: 메시지 설정 구현#309
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/exception/ErrorCode.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/controller/MessageSettingsController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/request/MessageSettingRequest.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/dto/response/MessageSettingResponse.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/MessageSettingsCommandService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageSettingsCommandServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/aggregate/MessageSettings.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/messages/command/domain/repository/MessageSettingRepository.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/users/command/application/controller/UserCommandController.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/messages/command/application/service/impl/MessageSettingsCommandServiceImplTest.java
Labels: enhancement

#318 [schedules] schedules 프론트 수정 #313
  be15_DevEagles_FE/src/features/schedules/components/ReservationForm.vue
  be15_DevEagles_FE/src/features/schedules/components/ScheduleRegistModal.vue
  be15_DevEagles_FE/src/features/schedules/views/ReservationListView.vue
  be15_DevEagles_FE/src/features/schedules/views/ReserveView.vue
  be15_DevEagles_FE/src/features/schedules/views/SchedulePlanLeaveView.vue
  be15_DevEagles_FE/src/features/schedules/views/SettingsReservation.vue
Labels: refactor

#320 [users] 회원 기능 구현 - 인증/인가 설정 구현 #316
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/config/SecurityConfig.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtAuthenticationFilter.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/JwtTokenProvider.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/RestAccessDeniedHandler.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/common/jwt/RestAuthenticationEntryPoint.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/controller/AuthController.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/model/CustomUser.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthService.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/AuthServiceImpl.java
  be15_DevEagles_BE/src/main/java/com/deveagles/be15_deveagles_be/features/auth/command/application/service/CustomUserDetailsService.java
  be15_DevEagles_BE/src/test/java/com/deveagles/be15_deveagles_be/features/auth/application/service/AuthServiceImplTest.java
  be15_DevEagles_FE/src/App.vue
  be15_DevEagles_FE/src/components/layout/TheHeader.vue
  be15_DevEagles_FE/src/features/users/views/AccountSettingView.vue
  be15_DevEagles_FE/src/features/users/views/LoginView.vue
  be15_DevEagles_FE/src/main.js
  be15_DevEagles_FE/src/plugins/axios.js
  be15_DevEagles_FE/src/store/auth.js
  be15_DevEagles_FE/src/store/userStatus.js
Labels: enhancement
